# Generated by Django 3.2 on 2022-04-04 16:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_stops'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuartiersCada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numquartie', models.SmallIntegerField(blank=True)),
                ('nomquartie', models.CharField(blank=True, max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
