# Generated by Django 3.2 on 2022-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_quartierscada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quartierscada',
            options={'ordering': ['nomquartie']},
        ),
        migrations.AlterField(
            model_name='quartierscada',
            name='nomquartie',
            field=models.CharField(max_length=100),
        ),
    ]
