# Generated by Django 3.2 on 2022-04-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_quartierscada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartierscada',
            name='nomquartie',
            field=models.CharField(max_length=100),
        ),
    ]
