# Generated by Django 3.2 on 2022-04-06 15:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20220406_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlotsCada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idgothing', models.IntegerField(blank=True)),
                ('numilot', models.IntegerField(blank=True)),
                ('numsecteur', models.IntegerField(blank=True)),
                ('nomsecteur', models.CharField(max_length=100)),
                ('numquartie', models.IntegerField(blank=True)),
                ('nomquartie', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'ordering': ['idgothing'],
            },
        ),
        migrations.CreateModel(
            name='SecteursCada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numsecteur', models.SmallIntegerField(blank=True)),
                ('nomsecteur', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'ordering': ['numsecteur'],
            },
        ),
    ]
